leftnav:
- identifier: feed6241-65a6-fe2f-cd1f-0a51b3bd438d
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 761373a2-dca4-7216-bf9c-b59f96891b6c
  name: Calendar
  pageRef: /pages/calendar/
  weight: 20
- identifier: efa92d06-493e-91ae-e8f3-6f9bac83b306
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 29aaf2dc-0764-549b-479a-a9798305c763
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 0b41b92a-1d18-bf08-608e-46e409bac8fe
  name: Projects
  pageRef: /pages/projects
  weight: 50
